import type { Finding, Severity } from '@/db/schema'

// ---------------------------------------------------------------------------
// NNG heuristic metadata
// ---------------------------------------------------------------------------

export const NNG_HEURISTICS: Record<number, string> = {
  1:  'Visibility of System Status',
  2:  'Match Between System and the Real World',
  3:  'User Control and Freedom',
  4:  'Consistency and Standards',
  5:  'Error Prevention',
  6:  'Recognition Rather Than Recall',
  7:  'Flexibility and Efficiency of Use',
  8:  'Aesthetic and Minimalist Design',
  9:  'Help Users Recognize, Diagnose, and Recover From Errors',
  10: 'Help and Documentation',
}

export const SEVERITY_ORDER: Severity[] = ['critical', 'serious', 'moderate', 'minor']

const SEVERITY_WEIGHT: Record<Severity, number> = {
  critical: 15,
  serious:  8,
  moderate: 3,
  minor:    1,
}

// ---------------------------------------------------------------------------
// UX Health Score
// ---------------------------------------------------------------------------

export interface HealthScore {
  score: number   // 0-100
  grade: 'A' | 'B' | 'C' | 'D' | 'F'
  label: string
  color: string   // tailwind text color
}

export function computeHealthScore(findings: Finding[]): HealthScore {
  const confirmed = findings.filter(f => f.status === 'confirmed')
  const deduction = confirmed.reduce(
    (sum, f) => sum + (SEVERITY_WEIGHT[f.severity as Severity] ?? 0),
    0,
  )
  const score = Math.max(0, 100 - deduction)

  let grade: HealthScore['grade']
  let label: string
  let color: string
  if (score >= 90) { grade = 'A'; label = 'Excellent'; color = 'text-green-400' }
  else if (score >= 75) { grade = 'B'; label = 'Good'; color = 'text-teal-400' }
  else if (score >= 60) { grade = 'C'; label = 'Needs Work'; color = 'text-yellow-400' }
  else if (score >= 40) { grade = 'D'; label = 'Poor'; color = 'text-orange-400' }
  else { grade = 'F'; label = 'Critical'; color = 'text-red-400' }

  return { score, grade, label, color }
}

// ---------------------------------------------------------------------------
// Heuristic heatmap data
// ---------------------------------------------------------------------------

export interface HeatmapCell {
  count: number
  severity: Severity
  heuristicId: number
}

export interface HeatmapRow {
  heuristicId: number
  label: string
  cells: Record<Severity, number>
  total: number
}

export function buildHeatmap(findings: Finding[]): HeatmapRow[] {
  // Only confirmed findings, only NNG for now
  const confirmed = findings.filter(f => f.status === 'confirmed' && f.framework === 'nng' && f.heuristicId != null)

  const rows: HeatmapRow[] = Object.entries(NNG_HEURISTICS).map(([id, label]) => {
    const hId = Number(id)
    const mine = confirmed.filter(f => f.heuristicId === hId)
    return {
      heuristicId: hId,
      label,
      cells: {
        critical: mine.filter(f => f.severity === 'critical').length,
        serious:  mine.filter(f => f.severity === 'serious').length,
        moderate: mine.filter(f => f.severity === 'moderate').length,
        minor:    mine.filter(f => f.severity === 'minor').length,
      },
      total: mine.length,
    }
  })

  // Only return rows with at least one finding, plus always show H1-H10 skeleton
  return rows
}

// ---------------------------------------------------------------------------
// Markdown export
// ---------------------------------------------------------------------------

export function buildMarkdown(findings: Finding[], flowName: string, stepNames: Record<string, string>): string {
  const actionable = findings
    .filter(f => f.status === 'confirmed' && (f.severity === 'critical' || f.severity === 'serious'))
    .sort((a, b) => {
      const order: Record<Severity, number> = { critical: 0, serious: 1, moderate: 2, minor: 3 }
      return order[a.severity as Severity] - order[b.severity as Severity]
    })

  const lines: string[] = [
    `## UX Audit: ${flowName}`,
    '',
    `> **${actionable.length} action items** (critical + serious confirmed findings)`,
    '',
    '| # | Step | Heuristic | Severity | Finding | Remediation |',
    '|---|------|-----------|----------|---------|-------------|',
  ]

  actionable.forEach((f, i) => {
    const heuristic = f.heuristicId ? `H${f.heuristicId}` : f.wcagCriterion ?? f.baymardCategory ?? f.framework
    const step = stepNames[f.stepId] ?? f.stepId
    const remediation = (f.remediation ?? f.recommendation ?? '').replace(/\|/g, '\\|').replace(/\n/g, ' ')
    const title = f.title.replace(/\|/g, '\\|')
    lines.push(`| ${i + 1} | ${step} | ${heuristic} | **${f.severity}** | ${title} | ${remediation} |`)
  })

  lines.push('', `---`, `*Generated by HeuristicEvaluator — ${new Date().toLocaleDateString()}*`)

  return lines.join('\n')
}
